"""20260121-01

Revision ID: 232efb99f63a
Revises: 
Create Date: 2026-01-21 12:31:39.925741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232efb99f63a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_activity_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    # ### end Alembic commands ###
