"""add problem track

Revision ID: d17c30156c1f
Revises: 232efb99f63a
Create Date: 2026-01-21 12:41:13.758645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17c30156c1f'
down_revision: Union[str, Sequence[str], None] = '232efb99f63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(length=50), nullable=False),
    sa.Column('problem_name', sa.String(length=500), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('pattern', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_problem_progress_user')
    )
    op.create_index(op.f('ix_problem_progress_id'), 'problem_progress', ['id'], unique=False)
    op.create_index(op.f('ix_problem_progress_problem_id'), 'problem_progress', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_progress_user_id'), 'problem_progress', ['user_id'], unique=False)
    op.add_column('progress', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('progress', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('progress', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'next_review_at')
    op.drop_column('progress', 'last_reviewed_at')
    op.drop_column('progress', 'review_count')
    op.drop_index(op.f('ix_problem_progress_user_id'), table_name='problem_progress')
    op.drop_index(op.f('ix_problem_progress_problem_id'), table_name='problem_progress')
    op.drop_index(op.f('ix_problem_progress_id'), table_name='problem_progress')
    op.drop_table('problem_progress')
    # ### end Alembic commands ###
